### ISSUE TITLE
Not compatible with Wampserver

### ISSUE THREAD

**Issue by infoweb-internet-solutions** [fishvision/yii2-migrate#3]
If i use this extension in a Yii2 installation that runs on a Wampserver new migration files are never detected. I'm pretty sure this has something to do with the different directory separator in a Windows environment.

**Comment by alexberriman** [comment]
Merged a fix in: https://github.com/fishvision/yii2-migrate/commit/7621ad1b2d122dd260b11dd1e7dbe3d8cf02a281

**Comment by infoweb-internet-solutions** [comment]
Thx for the fix!
